language: generic 
sudo: required // use superuser account for execute
services:
  - docker // required dependency that must exist

before_install: 
  - docker build -t mhalkaaf/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true mhalkaaf/react-test npm test

after_success: 
  - docker build -t mhalkaaf/fiboclient ./client
  - docker build -t mhalkaaf/fibonginx ./nginx 
  - docker build -t mhalkaaf/fiboserver ./server 
  - docker build -t mhalkaaf/fiboworker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push mhalkaaf/fiboclient
  - docker push mhalkaaf/fibonginx
  - docker push mhalkaaf/fiboserver
  - docker push mhalkaaf/fiboworker